### ISSUE TITLE
Many gpu error

### ISSUE THREAD

**Issue by tinhchuquang** [leondgarse/Keras_insightface#3]
I use many gpu and code show error:
File "/home/tinhcq/Keras_insightface/evals.py", line 57, in __do_predict_distribute__
    pp = self.basic_model.make_predict_function()
AttributeError: 'Model' object has no attribute 'make_predict_function'

You can fix this? Thank

**Comment by leondgarse** [comment]
Which tf version you are using? `make_predict_function` works on `tf-nightly` / `tf 2.2.0`, but **not** `tf 1.15.0`, As far as I remember, neither the normal predict function `model.predict` works well on `tf 1.15.0` under `tf.distribute.MirroredStrategy` stratrgy.

**Comment by tinhchuquang** [comment]
Okie, Thanks, I use tensorflow 2.0.0 so function make_predict_function is None.

**Comment by tinhchuquang** [comment]
Hello, I use tensorflow version 2.2.0 and training mutil-gpu with arcface loss. Have the error as below:
" ValueError: You must specify an aggregation method to update a MirroredVariable in Replica Context. You can do so by passing an explicit value for argument `aggregation` to tf.Variable(..).e.g. `tf.Variable(..., aggregation=tf.VariableAggregation.SUM)``tf.VariableAggregation` lists the possible aggregation methods.This is required because MirroredVariable should always be kept in sync. When updating them or assigning to them in a replica context, we automatically try to aggregate the values before updating the variable. For this aggregation, we need to know the aggregation method. Another alternative is to not try to update such MirroredVariable in replica context, but in cross replica context. You can enter cross replica context by calling `tf.distribute.get_replica_context().merge_call(merge_fn, ..)`.Inside `merge_fn`, you can then update the MirroredVariable using `tf.distribute.StrategyExtended.update()`".

Do you have error that?

**Comment by leondgarse** [comment]
Can you share me your full script? I've tested the basic train, which is OK.
```py
import train, data, losses
with tf.distribute.MirroredStrategy().scope():
    data_path = 'faces_emore_test'
    eval_paths = ['lfw.bin']
    basic_model = train.buildin_models("MobileNet", dropout=0.4, emb_shape=256)
    tt = train.Train(data_path, save_path='keras_mobile_facenet_emore.h5', eval_paths=eval_paths, basic_model=basic_model, lr_base=0.001, batch_size=512, random_status=3)
    sch = [{"loss": losses.ArcfaceLoss(), "epoch": 5}]
    tt.train(sch, 0)
```
But meet that seem error if I enable `centerloss`
```py
sch = [{"loss": losses.ArcfaceLoss(), "centerloss": True, "epoch": 5}]
```

**Comment by leondgarse** [comment]
OK， I just made a checkin to fix this, but with many other stuffs, changes in [losses.py](https://github.com/leondgarse/Keras_insightface/commit/cc0dec91749f3bd1b148028c4049c1a52d3cdb9c#diff-412ff816c7b5bfd34c7409700dcd8200) is to fix this issue. You can take a try.

**Comment by tinhchuquang** [comment]
Many thanks, Master. I try, and problem is solved.

**Comment by leondgarse** [comment]
Um... wait, I'm not sure should this be `SUM`
```py
centers = tf.Variable(tf.zeros([num_classes, feature_dim]), trainable=False, aggregation=tf.VariableAggregation.SUM)
```
or `MEAN`
```py
centers = tf.Variable(tf.zeros([num_classes, feature_dim]), trainable=False, aggregation=tf.VariableAggregation.MEAN)
```
Need a test here.

**Comment by tinhchuquang** [comment]
I Think Sum is correct, because  in your code "loss = tf.reduce_mean(tf.square(embedding - centers_batch), axis=-1) * self.factor", 
This is an average of 1 time, if you leave it as "mean" then you will calculate 2 times the average.

**Comment by leondgarse** [comment]
I made some tests and the result shows it should be `MEAN`, and I just made a checkin.
- Using `SUM`, `centerloss` will soon be `NAN`...
- Using `MEAN`, I multiply `diff` in `centerloss` by `num_replicas`, this seems better, and my train result seems OK.
